# Taps
tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'nicoverbruggen/homebrew-cask'

# Development
brew 'php'
# brew 'php@7.4'
# brew 'php@7.3'
# brew 'php@7.2'
brew 'php@8.1'
brew 'php@8.2'
brew 'composer'
brew 'dnsmasq'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'nvm'
brew 'autojump'
brew 'redis'

# Apps
# cask '1password'
# cask 'alfred'
# cask 'discord'
# cask 'docker'
# cask 'dropbox'
cask 'github'
cask 'google-chrome'
cask 'iterm2'
# cask 'notion'
# cask 'phpmon'
cask 'postman'
# cask 'slack'
# cask 'spotify'
cask 'tableplus'
# cask 'telegram-desktop'
# cask 'tinkerwel'
cask 'visual-studio-code'
